# Generated by Django 3.2.4 on 2021-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('temp', 'Tempoary'), ('feat.', 'Feature')], default='temp', max_length=32)),
            ],
        ),
        migrations.AlterModelOptions(
            name='exhibit',
            options={'verbose_name_plural': 'exhibit_status'},
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='exhibit_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'visitor'), (2, 'staff'), (3, 'curator'), (4, 'admin')], null=True),
        ),
    ]
