# Generated by Django 3.2.4 on 2021-07-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Porfile',
            new_name='User_Profile',
        ),
    ]
