# Generated by Django 3.2.4 on 2021-07-08 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_user_porfile_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('exhibits', models.ManyToManyField(to='adminapp.Exhibit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribe_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
