# Generated by Django 3.2.4 on 2021-07-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_auto_20210709_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibit',
            options={'verbose_name_plural': 'Exhibit'},
        ),
    ]
