# Generated by Django 3.2.4 on 2021-07-14 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
