# Generated by Django 3.2.4 on 2021-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_auto_20210714_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_curator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'VISITOR'), (2, 'STAFF'), (3, 'CURATOR')], default=1, null=True),
        ),
    ]
