# Generated by Django 3.2.4 on 2021-07-19 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_alter_question_user'),
        ('adminapp', '0016_question_answered'),
    ]

    operations = [
    ]
