# Generated by Django 3.2.4 on 2021-07-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_merge_0016_alter_question_user_0016_question_answered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
